### PR TITLE
show item details when creating and deleting

### LINKED ISSUE #410: Show diff for new files?
Currently, the user just gets a `will be created` message for newly created files. Is this really a good idea? Why hide the content?

Hiding the content can kill the workflow and leave admins wondering: "Okay, a new file, but what's in it? I'd like to know. Now I'll have to check manually."

I'm aware that `status.must_be_created` is used in a lot of places ... This change request might not be as trivial as it seems.

### PR DESCRIPTION
**Pull request by trehn**
fixes #410

### CODE REVIEW

**Comment by Kunsi** [comment]
Would it be possible to get an environment Variable to always show diffs? I think i'm not the only one who'd like to enable this by default.

**Comment by trehn** [comment]
> Would it be possible to get an environment Variable to always show diffs? I think i'm not the only one who'd like to enable this by default.

Nah, I'd rather show diffs by default and inverted the CLI switches instead.

**Comment by Kunsi** [comment]
I'm missing the `<node>` and `<bundlewrap>` identifiers in the generated diffs, can you please add them again? It's very difficult to see what will change here:
```
✘ ovh.icinga2  icinga2  file:/etc/icinga2/scripts/icinga_notification_wrapper  (content)
│ 
│ content
│ @@ -90,7 +90,6 @@
│  
│  
│  def notify_per_mail():
│ -    # editorconfig-checker-disable
│      text = """
│      _      _
│     (_)____(_)___  ____ _____ _
│ @@ -109,7 +108,6 @@
│  State: {state}
│  
│  {output}"""
│ -    # editorconfig-checker-enable
│  
│      mail = email.mime.text.MIMEText(text.format(
│              host=args.host_name,
```
(locally added comments, not yet applied to the node)

**Comment by Kunsi** [comment]
Also, there seems to be a concurrency issue:
```
✘ home.router  apt  file:/etc/kernel/postinst.d/unattended-upgrades  (content)
│ 
│ +# / /_/ / /_/ / / / / /_/ / /  __/ |/ |/ / /  / /_/ / /_/ /
│ +#/_.___/\__,_/_/ /_/\__,_/_/\___/|__/|__/_/   \__,_/ .___/
│ +#                                                 /_/
│ +#
│  # CAUTION! This file is managed with bundlewrap.
│  # Any manual edits will be lost!
│  
│ 
│ 
│ -# editorconfig-checker-disable-file
│ content
│ @@ -3,8 +3,8 @@
│  # check_nginx_status.pl
│  # Author  : regis.leroy at makina-corpus.com
│  # /etc/kernel/postinst.d/unattended-upgrades
✘ htz-cloud.pirmasens  cron  file:/etc/crontab  (content)
│ 
│  
│  case "$DPKG_MAINTSCRIPT_PACKAGE::$DPKG_MAINTSCRIPT_NAME" in
│ content
│ @@ -1,3 +1,10 @@
│ +#     __                    ____
│ +#   / /_  __  ______  ____/ / /__ _      ___________ _____
│  # Licence : GPL - http://www.fsf.org/licenses/gpl.txt
│ @@ -412,14 +411,14 @@
│      $InfoData = sprintf (" %.3f sec. response time, Active: %d (Writing: %d Reading: %d Waiting: %d)"
│ -    linux-image-extra*::postrm)
│ -        exit 0;;
│ +   linux-image-extra*::postrm)
│ +      exit 0;;
│  esac
│  
│  if [ -d /var/run ]; then
│ 
│ +#  / __ \/ / / / __ \/ __  / / _ \ | /| / / ___/ __ `/ __ \ 
│ +# / /_/ / /_/ / / / / /_/ / /  __/ |/ |/ / /  / /_/ / /_/ /
```

This diff is clearly unusable.

**Comment by trehn** [comment]
> I'm missing the `<node>` and `<bundlewrap>` identifiers in the generated diffs, can you please add them again? It's very difficult to see what will change here:

The diff was just accidentally inverted, fixed. All diffs now show what bw wants to do.

**Comment by trehn** [comment]
> Also, there seems to be a concurrency issue:

Fixed as well.

**Pull request merged**
