### PR TITLE
Exclude dummy nodes from `bw lock`

### PR DESCRIPTION
**Pull request by vain**
CC #333.

### CODE REVIEW

**Comment by trehn** [comment]
This introduces some asymmetry. `bw apply` and `bw verify` will tell you that a dummy node "has no items", while this just silently skips dummy nodes.

**Comment by vain** [comment]
I've pushed an alternative fac^W implementation that handles dummy nodes in `lock.py`.

This feels a little convoluted, though. IMHO, it would be easier to have a little function in `cmdline/lock.py` that filters all dummy nodes and prints that `has no items` line. This function would be called from `bw_lock_add` and friends. How about that?

**Comment by trehn** [comment]
👍

**Comment by trehn** [comment]
thx

**Pull request merged**
