### PR TITLE
Secrets

### PR DESCRIPTION
**Pull request by trehn**
PR for #220

### CODE REVIEW

**Comment by vain** [comment]
I'm having trouble with items not being skipped if the key is not available.

I'm defining a simple file in a newly created repo:

    files = {
        '/etc/jo': {
            'content_type': 'mako',
        },
    }

The template's content:

    ${repo.vault.password_for("welt", key="devops")}

A key "devops" does not exist. As far as I understand, the item should be skipped. However:

    ! TemplateError("Error while rendering template for node1:foo:file:/etc/jo: Key 'devops' not available to generate password 'welt', check your .secrets.cfg",)

I also cannot access `vault` in node metadata. I *guess* something like this is missing:

```diff
diff --git a/bundlewrap/repo.py b/bundlewrap/repo.py
index 6b6c62b..c49a483 100644
--- a/bundlewrap/repo.py
+++ b/bundlewrap/repo.py
@@ -235,7 +235,7 @@ class LibsProxy(object):
         self.__path = state
 
 
-def nodes_from_file(filepath, libs, repo_path):
+def nodes_from_file(filepath, libs, repo_path, vault):
     """
     Returns a list of nodes as defined in the given nodes.py.
     """
@@ -243,7 +243,7 @@ def nodes_from_file(filepath, libs, repo_path):
         flat_node_dict = utils.getattr_from_file(
             filepath,
             'nodes',
-            base_env={'libs': libs, 'repo_path': repo_path},
+            base_env={'libs': libs, 'repo_path': repo_path, 'vault': vault},
         )
     except KeyError:
         raise RepositoryError(
@@ -458,7 +458,7 @@ class Repository(object):
 
         # populate nodes
         self.node_dict = {}
-        for node in nodes_from_file(self.nodes_file, self.libs, self.path):
+        for node in nodes_from_file(self.nodes_file, self.libs, self.path, self.vault):
             self.add_node(node)
 
     @utils.cached_property
```

**Comment by trehn** [comment]
Damn, the template thing is a real problem because Mako eats our exception and turns it into a generic TemplateError...

**Comment by vain** [comment]
Yep, works as intended now. :) Let's merge this!

**Comment by trehn** [comment]
Oh come on... https://travis-ci.org/bundlewrap/bundlewrap/jobs/115654253

**Pull request merged**
