### PR TITLE
[WIP] OpenBSD compatibility

### PR DESCRIPTION
**Pull request by timbuchwaldt**
This pull request introduces support for OpenBSD.

Todo:

- [x] Documentation
- [x] CLA
- [x] Add pkg_openbsd
- [x] Add svc_rcd

### CODE REVIEW

**Comment by timbuchwaldt** [comment]
I would suggest the following to refactor the inline if-switches on top of all items that need it:
```python
def os_dependent(os):
    if os == "openbsd":
        return {
           "chown_command": "chown {}{} {}"
        }
    elif os == "otheros":
        return {
           "chown_command": "chown {}{} {}"
        }
    else:
        return {
           "chown_command": "chown {}{} -- {}"
        }
```

In the logic itself the if/else branches would go away in favor of `os_dependent(self.node.os)["chown_command"]`

**Comment by trehn** [comment]
Is there a good reason for changing the non-OpenBSD `_DEFAULT_SALT`?

The docs for `use_shadow` should reflect that it does nothing when `node.os` is `openbsd`.

**Comment by trehn** [comment]
The new items must also be added to `docs/content/repo/bundles.md`.

**Comment by timbuchwaldt** [comment]
RE changing the default salt: Nope, was trying out and forgot. Will update the docs.

**Comment by vain** [comment]
Gave it a try on an OpenBSD 5.9 VM, looks good to me. :)

Two details:

-   `svc_rcd.py`, function `svc_enabled()`: Wouldn't it be better to use `"rcctl ls on | grep ^{}$"` to avoid partial matches?
-   `svc_rcd.md`: The docs still contain systemd examples, i.e. `fcron.service` and `sgopherd.socket`. That might be a little confusing.

(Maybe we can find a better term than `svc_rcd`. `/etc/rc.d` is available on many systems, including GNU. They all work slightly different, though.)

**Comment by timbuchwaldt** [comment]
@vain Cool! :)

Will change both. The slight differences concern me, too. Maybe svc_openbsd would be more clear, as it states on which OS it works. Or adding compatibility to e.g. Gentoo - but I have no motivation to do that TBH.

**Comment by trehn** [comment]
Thanks! :lovetim:

**Pull request merged**
