### PR TITLE
Soft locks

### PR DESCRIPTION
**Pull request by trehn**
PR for #191 

The existing lock is now called a "hard lock" because it continues to prevent concurrent apply operations on the node, regardless of which user it is. These new locks are "soft locks" because they are ignored by the users who created them.

As of now, the management UI for the soft locks is in place. TODO:

* [x] remove expired locks in `softlock_list()`
* [x] check `softlock_list()` at the beginning of `bw run` and `bw apply`
* [ ] think about a good default expiry timeframe, maybe 12h is better than 8h
* [x] docs
* [ ] tests

### CODE REVIEW

**Comment by trehn** [comment]
One remaining problem with a busy pull request workflow is that while I can now lock certain nodes and make them accessible to *me*, that doesn't lock these nodes to other *branches* I might be working on. But I believe the only way around that would be deep git integration (no) or manually "tagging" each `bw apply` with a branch name (no).

**Comment by vain** [comment]
Currently reviewing.

> One remaining problem with a busy pull request workflow is that while I can now lock certain nodes and make them accessible to me, that doesn't lock these nodes to other branches I might be working on.

Let's encourage the users to cheat and brutally abuse `$BW_IDENTITY` (kidding, kind of).

**Comment by vain** [comment]
Buggy McBugface:

```
# l bundlewrap.softlock.d/
total 12,288
drwxr-xr-x 2 root     root      4,096 May 16 18:43 ./
drwxrwxrwt 4 root     root      4,096 May 16 18:43 ../
-rw------- 1 lulufant hellyeah    135 May 16 18:43 KAQE
```

But:

```
        cat = node.run("cat {}".format(SOFT_LOCK_FILE.format(id="*")), may_fail=True)
        if cat.return_code != 0:
            return []
```

Meaning, when another user puts a lock on the system, my `cat` will yield a `Permission denied` with exit code 1, so my `bw` ignores the other user's lock.

Easy to fix, just upload locks with `mode=0644`.

**Comment by vain** [comment]
:+1: for everything else. This is going to be a huge improvement. :)

**Comment by vain** [comment]
>> One remaining problem with a busy pull request workflow is that while I can now lock certain nodes and make them accessible to me, that doesn't lock these nodes to other branches I might be working on.

> Let's encourage the users to cheat and brutally abuse `$BW_IDENTITY` (kidding, kind of).

On a more serious note: https://github.com/vain/bin-pub/commit/e403b0fdb8d4d03b879139988407991984159a93

I don't think there's a way to avoid "local tooling" like this, unless we want to support each and every VCS (including NO VCS) in bw.

**Comment by trehn** [comment]
Random idea: Maybe instead of the current choice between "run", "apply", or both we can just add item selectors to locks. One could still lock down a node completely by using `*`, but it would be possible to prevent changes to specific "small" items like zonefiles or just a certain bundle (with `bundle:foo`) while still allowing the rest of the node to be managed. The locked items would just be skipped.

I'm not sure there is a need to prevent `bw run`.

**Comment by trehn** [comment]
@vain care for a final review?

**Comment by vain** [comment]
Works like a charm.

I've also added support for `$BW_SOFTLOCK_EXPIRY`. Want me to push it? Or is that a bad idea? People might set this to "three weeks" so they can be lazy. But it would allow for a better adaption to the team's workflow ...

**Comment by trehn** [comment]
By all means, push it. Was just too tired to add that on top. I have another almost complete commit that will show the default defaults or the defaults from env vars in `--help` for all commands. Add your stuff, then I can complete that.

**Pull request merged**
