### PR TITLE
Warn about unused bundles

### PR DESCRIPTION
**Pull request by vain**
CC #208

### CODE REVIEW

**Comment by trehn** [comment]
I think it would be better to put this towards the end of the output, so it doesn't scroll by too quickly...

**Comment by vain** [comment]
Fun fact: I deliberately put it at the beginning because it's just a set of mildly important warnings and it's very fine if it scrolls by. %)

I'm fine with both, though. Will change.

**Comment by vain** [comment]
Thinking about it ... it would be nice to have a quick way to check for orphaned bundles without having to test *everything*. (This was a nice side effect of my initial version.)

Maybe move the output for orphaned bundles to the end and add a command line switch `--only-orphaned-bundles` which omits all other tests?

**Comment by trehn** [comment]
oh and please add a TODO for making this an error in some way (maybe with a CLI switch) in 3.0

**Comment by trehn** [comment]
nah, just leave it at the beginning then

**Comment by trehn** [comment]
I think in 3.0 we need to come up with a more flexible way of specifiying which tests should be run.

**Comment by trehn** [comment]
LGTM, waiting for build

**Pull request merged**
